### ISSUE TITLE
Getting  Current User Info

### ISSUE THREAD

**Issue by francis-fullstack** [James-Machouk/azure-ad-auth#4]
How do you fetch theuser  information after succesfully login? I need to insert it on database

**Comment by James-Machouk** [comment]
hello @francis-fullstack, by default, this package pulls data from Azure using Microsoft Graph ( https://graph.microsoft.com/v1.0/me ) and creates a new user " if not exists" using ( userPrincipalName, displayName & id ),
You can use Microsoft Graph to pull any data that suit your needs. 
check this  [https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent](Scops)
